[tool:pytest]
filterwarnings =
    ignore:.*coroutine.*was never awaited.*:RuntimeWarning
    ignore:.*return a value that is not None.*:DeprecationWarning
    ignore:.*MessageMapContainer.*:DeprecationWarning
    ignore:.*ScalarMapContainer.*:DeprecationWarning
asyncio_mode = auto
